name: build-deploy

on:
     push:
        branches: [ main ]

jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout
             uses: actions/setup-node@v2
            #  with:
            #   node-version: 20

           - name: Install dependencies
             run: npm install 
           - run: npm ci
           - run: npm run build
